[BUGFIX] Enable DI for deprecated `EXT:install` update classes
With #106956 the upgrade wizards were relocated from EXT:install
to EXT:core, and aliased with their own FQCNs.

However, utilizing e.g.
`TYPO3\CMS\Install\Updates\DatabaseUpdatedPrerequisite` in the
`getPrerequisites()` method of an upgrade wizard would lead
to a dependency injection error:

```
Uncaught TYPO3 Exception Too few arguments to function
TYPO3\CMS\Core\Upgrades\DatabaseUpdatedPrerequisite::__construct(),
0 passed in /var/www/html/typo3-core/typo3/sysext/core/Classes/
Utility/GeneralUtility.php on line 2885 and exactly 2 expected
thrown in file /var/www/html/typo3-core/typo3/sysext/core/Classes/
Upgrades/DatabaseUpdatedPrerequisite.php in line 35
```

This patch inserts the proper DI resource location in the service
definition so it can be utilized for aliasing.

Resolves: #109649
Related: #106947
Related: #106956
Related: #106963
Related: #106957
Releases: main
Change-Id: I2a9d313331fcd1484418169882864f9a1a2ba893
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/93742
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Garvin Hicking <garvin@hick.ing>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Garvin Hicking <garvin@hick.ing>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>